### ISSUE TITLE
Fork diverged

### ISSUE THREAD

**Issue by albertored** [lboekhorst/cloud_watch#10]
Hi, I'm ready to submit a pull request with metadata filtering and matching feature but I just saw @pmenhart fork and it has some interesting features that I would like to use in my code.

@pmenhart what do you think about pushing your code in this repo (or @lboekhorst the other way around)? I think it would be more useful for the community to have a single repo with all developed features.

**Comment by pmenhart** [comment]
I can (and should) update and push [Added dynamic log stream names](https://github.com/pmenhart/cloud_watch/commit/9039c8201473aefdbdc2c9eb4eeade1ce9bbe93e) and perhaps [Performance optimizations](https://github.com/pmenhart/cloud_watch/commit/f3333371b2b36f3ec50be4222218268b502c18a4). 

But I am not sure how useful are the other commits, which are dealing with various ExAws errors we experienced under high load (hundreds of log messages per seconds). I consider these changes experimental and not tested well (e.g. no tests with the [AWS](https://github.com/jkakar/aws-elixir) library). 
It would be definitely useful to get some usage reports or other feedback, before considering merging them into the main repo.

**Comment by albertored** [comment]
Thanks @pmenhart! I agree that those two commits are the more suitable for being included here. Maybe also [Handling AWS error 400](https://github.com/pmenhart/cloud_watch/commit/3f56bf6639fa55137359d80dc97746eb6459b44e)? I let you decide

**Comment by pmenhart** [comment]
I created PR #11 with the two commits that should be generally useful. 

As for the rest... I am afraid we don't have good solution for high log rates. AWS CloudWatch request takes a long time (even longer with error re-tries), dragging down the whole Logger. I am thinking about a substantial rewrite where the AWS request is handled by a separate GenServer process.

In the meantime, my suggestion would be to use the current release. Fix only the problems you encounter in your operation - feel free to try some of my experimental commits. Or open a ticket here, we'll try to help.

**Comment by albertored** [comment]
Perfect, thanks!

**Comment by lboekhorst** [comment]
Hi @albertored,

I have just merged the changes by @pmenhart. I will push to Hex later today. Later this week, I will consolidate our efforts into a new organisation and make sure our efforts stay aligned. Thanks for pointing this out and if you have any other issues, please let us know!
