### ISSUE TITLE
CloudWatch logs wants UTC, but local time is being passed.

### ISSUE THREAD

**Issue by ijcd** [lboekhorst/cloud_watch#4]
The logs are showing up in the console with local time, not UTC.

**Comment by lboekhorst** [comment]
Hi @ijcd,

I will take a look at it this week. I have merged your other changes in for now, so you can pull from `master` to get the fixes in your app. I will push a new version to Hex as soon as I get this issue closed.

Thanks!

**Comment by lboekhorst** [comment]
When the event is logged with the handler, any information regarding timezone is lost. For CloudWatch, it's important to specify that logging needs to be in UTC: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L118. I've added this to the README and published 0.2.6 to Hex. If you have any further problems, please let me know!
